const SET_USER = "SET_USER";
const LOAD_USER = "LOAD_USER";
const SIGN_UP = "SIGN_UP";
const EMAIL_VERIFIED = "EMAIL_VERIFIED";
const SIGN_IN = "SIGN_IN";

export {
    SET_USER, LOAD_USER,
    SIGN_UP,
    EMAIL_VERIFIED,
    SIGN_IN,
}